const animals = [
            {
                id: 1,
                name: "Jaguár",
                latinName: "Panthera onca",
                category: "mammal",
                image: "./kepek/allatok/jaguar.jpg",
                badge: "Emlős",
                description: "A jaguár Amerika legnagyobb ragadozó macskája, és az esőerdők csúcsragadozója.",
                weight: "56-96 kg",
                habitat: "Esőerdők",
                lifespan: "12-15 év",
                conservation: "near-threatened",
                conservationText: "Közeli veszély",
                fullDescription: "A jaguár Latin-Amerika legnagyobb macskafélé ragadozója. Jellegzetessége az erőteljes állkapcsa, amellyel akár teknős páncélját is át tudja törni. Magányos vadász, aki remekül úszik és mászik.",
                diet: "Húsevő - kapibarák, pekárik, őzek, teknősök, kaimánok",
                behavior: "Magányos, éjszakai vadász. Territoriális, saját területet véd. Kiváló úszó.",
                threats: "Élőhely elvesztése, illegális vadászat, konfliktus emberekkel"
            },
            {
                id: 2,
                name: "Kékarcú Ara",
                latinName: "Ara ararauna",
                category: "bird",
                image: "./kepek/allatok/ara.jpg",
                badge: "Madár",
                description: "Ez a lenyűgöző papagáj élénk színeivel és intelligenciájával hódítja meg az embereket.",
                weight: "0.9-1.3 kg",
                habitat: "Esőerdő lombkorona",
                lifespan: "50-70 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A kékarcú ara az egyik legismertebb papagájfaj. Jellegzetes kék és sárga tollazata messziről felismerhető. Párokba verődve élnek, és egy életre szóló kapcsolatot alakítanak ki.",
                diet: "Gyümölcsök, magvak, diók, virágok",
                behavior: "Társas madár, párban él. Hangos, csapatokban táplálkozik. Rendkívül intelligens.",
                threats: "Illegális kereskedelem, élőhely vesztés, fogság miatti stressz"
            },
            {
                id: 3,
                name: "Vörös Szemű Levelibéka",
                latinName: "Agalychnis callidryas",
                category: "amphibian",
                image: "./kepek/allatok/levelibeka.jpg",
                badge: "Kétéltű",
                description: "Élénk színeivel az esőerdők egyik legikonikusabb állata, amely a ragadozókat riasztja el.",
                weight: "6-20 g",
                habitat: "Esőerdő fák",
                lifespan: "5 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "Ez a kis levelibéka éjszaka aktív. Vörös szeme és élénk zöld teste figyelmeztetés a ragadozóknak. Tapadókorongjaival könnyedén mászik a fákon.",
                diet: "Rovarok, lepkék, legyek, szúnyogok",
                behavior: "Éjszakai. Fákon él, kiváló mászó. Esős évszakban szaporodik.",
                threats: "Élőhely vesztése, éghajlatváltozás, gombás fertőzések"
            },
            {
                id: 4,
                name: "Lajhár",
                latinName: "Bradypus variegatus",
                category: "mammal",
                image: "./kepek/allatok/lajhar.jpg",
                badge: "Emlős",
                description: "A világ egyik leglassabb mozgású állata, amely szinte egész életét a fákon tölti.",
                weight: "3.5-6 kg",
                habitat: "Lombkorona",
                lifespan: "20-30 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A háromujjú lajhár szinte mozdulatlan életmódot folytat, napi 15-20 órát alszik. Lassú anyagcseréje miatt hetente egyszer száll le a földre. Bundájában alga él, ami zöldes színt ad neki.",
                diet: "Növényevő - levelek, hajtások, gyümölcsök",
                behavior: "Magányos, rendkívül lassú mozgás. Hetente egyszer ereszkedik le.",
                threats: "Élőhely vesztése, közlekedési balesetek, elektromos vezetékek"
            },
            {
                id: 5,
                name: "Zöld Anakonda",
                latinName: "Eunectes murinus",
                category: "reptile",
                image: "./kepek/allatok/anakonda.jpg",
                badge: "Hüllő",
                description: "A világ legnagyobb kígyója, amely vízben és szárazföldön egyaránt otthonosan mozog.",
                weight: "30-70 kg",
                habitat: "Folyók, mocsarak",
                lifespan: "10-30 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A zöld anakonda elérheti a 9 méter hosszúságot is. Nem mérges, áldozatát összeszorítással öli meg. Kiváló úszó, vízben vadászik zsákmányára.",
                diet: "Húsevő - rágcsálók, madarak, halak, kaimánok",
                behavior: "Magányos, vízhez kötődő. Éjszaka aktív vadász. Tojások helyett élő utódokat szül.",
                threats: "Bőréért való vadászat, élőhely elvesztése, tévhitek miatti üldözés"
            },
            {
                id: 6,
                name: "Tukán",
                latinName: "Ramphastos toco",
                category: "bird",
                image: "./kepek/allatok/tukan.jpg",
                badge: "Madár",
                description: "Óriási, színes csőrével az egyik legfelismerhetőbb trópusi madár.",
                weight: "500-860 g",
                habitat: "Erdő lombkorona",
                lifespan: "20 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A tukán csőre aránytalanul nagynak tűnik, de valójában üreges és könnyű. Hőszabályozásra is használja. Társas madár, kis csoportokban él.",
                diet: "Gyümölcsevő - főleg bogyók, kisebb rovarok, tojások",
                behavior: "Társas, csoportokban él. Játékos, csőrével dobálja egymásnak a gyümölcsöt.",
                threats: "Élőhely vesztése, illegális kereskedelem, turisták általi zavarás"
            },
            {
                id: 7,
                name: "Ocelot",
                latinName: "Leopardus pardalis",
                category: "mammal",
                image: "./kepek/allatok/ocelot.jpg",
                badge: "Emlős",
                description: "Kis termetű ragadozó macska gyönyörű foltos bundával és éles vadászösztönnel.",
                weight: "8-16 kg",
                habitat: "Esőerdő aljnövényzet",
                lifespan: "10-13 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "Az ocelot éjszakai vadász, nappal a növényzet sűrűjében pihen. Minden egyed foltmintázata egyedi, akár az emberi ujjlenyomat. Kitűnő fára mászó.",
                diet: "Húsevő - rágcsálók, madarak, hüllők, halak",
                behavior: "Magányos, territoriális. Éjszakai vadász. Kitűnő mászó és úszó.",
                threats: "Bőréért való vadászat, élőhely elvesztése, közúti balesetek"
            },
            {
                id: 8,
                name: "Méregbéka",
                latinName: "Dendrobates tinctorius",
                category: "amphibian",
                image: "./kepek/allatok/meregbeka.jpg",
                badge: "Kétéltű",
                description: "Apró, de halálos: élénk színei figyelmeztetnek erős méreganyagaira.",
                weight: "2-7 g",
                habitat: "Esőerdő talaj",
                lifespan: "3-5 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A méregbékák bőre erős alkaloid méreganyagokat tartalmaz, amelyeket táplálékukból nyernek. Fogságban tartott egyedek nem mérgezők, mert nem jutnak hozzá a megfelelő rovarokhoz.",
                diet: "Rovarevő - hangyák, atkák, termeszek, kis bogarak",
                behavior: "Nappali aktivitás. Gondoskodó szülő, petéket őrzi. Territoriális.",
                threats: "Élőhely vesztése, illegális kereskedelem, éghajlatváltozás"
            },
            {
                id: 9,
                name: "Hárpia",
                latinName: "Harpia harpyja",
                category: "bird",
                image: "./kepek/allatok/harpia.jpg",
                badge: "Madár",
                description: "Az esőerdő legerősebb ragadozó madara, hatalmas karmaival lajhárt is el tud kapni.",
                weight: "6-9 kg",
                habitat: "Magas fák",
                lifespan: "25-35 év",
                conservation: "near-threatened",
                conservationText: "Közeli veszély",
                fullDescription: "A hárpia karmai nagyobbak, mint egy medve karmai. Hihetetlen sebességgel repül a sűrű erdőben, és nagy emlősöket is zsákmányul ejt. Egy pár egész életében együtt marad.",
                diet: "Húsevó - lajhárok, majmok, agutik, papagájok",
                behavior: "Párban él, hűséges. Lassú szaporodás - 2-3 évente 1 tojás.",
                threats: "Élőhely vesztése, fészkek kivágása, üldözés"
            },
            {
                id: 10,
                name: "Kapibara",
                latinName: "Hydrochoerus hydrochaeris",
                category: "mammal",
                image: "./kepek/allatok/kapibara.jpg",
                badge: "Emlős",
                description: "A világ legnagyobb rágcsálója, amely vízben és szárazföldön egyaránt otthonosan mozog.",
                weight: "35-66 kg",
                habitat: "Folyók, tavak",
                lifespan: "8-10 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A kapibara társas állat, 10-20 egyedből álló csoportokban él. Félig vízi életmódot folytat, szeme és orra a feje tetején van, így vízben is tud lélegezni. Békés természetű, más állatokkal jól kijön.",
                diet: "Növényevő - füvek, vízinövények, gyümölcsök, fakéreg",
                behavior: "Társas, csoportokban él. Nappal alszik, éjjel aktív. Kiváló úszó.",
                threats: "Húsáért való vadászat, élőhely vesztése, betegségek"
            },
            {
                id: 11,
                name: "Basiliscus",
                latinName: "Basiliscus plumifrons",
                category: "reptile",
                image: "./kepek/allatok/basiliscus.jpg",
                badge: "Hüllő",
                description: "A basiliscus gyík képes a víz felszínén futva közlekedni.",
                weight: "200-600 g",
                habitat: "Folyóparti erdők",
                lifespan: "7-10 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A baziliszkusz hátsó lábain található különleges börtyék segítségével akár 5 métert is képes futni a víz felszínén. Ez a képesség ragadozók elől való menekülésre szolgál.",
                diet: "Mindenevő - rovarok, kisebb gyíkok, gyümölcsök, virágok",
                behavior: "Nappali. Fákon és földön él. Vízbe ugrik veszély esetén.",
                threats: "Élőhely vesztése, terráriumi kereskedelem, ragadozók"
            },
            {
                id: 12,
                name: "Tamandua",
                latinName: "Tamandua tetradactyla",
                category: "mammal",
                image: "./kepek/allatok/tamandua.jpg",
                badge: "Emlős",
                description: "A hangyászmajom hosszú nyelvével és erős karmaival a termeszekre vadászik.",
                weight: "3-7 kg",
                habitat: "Erdők, szavannák",
                lifespan: "9-16 év",
                conservation: "least-concern",
                conservationText: "Nem veszélyeztetett",
                fullDescription: "A tamandua 40 cm hosszú, ragacsos nyelvével naponta több ezer hangyát és termeszt fogyaszt. Erős mellső lábai hangyabolyok feltépésére, valamint védekezésre szolgálnak. Fogai nincsenek.",
                diet: "Rovarevő - hangyák, termeszek, méhek",
                behavior: "Magányos, nappal és éjjel aktív. Fákon és földön egyaránt él.",
                threats: "Közlekedési balesetek, élőhely elvesztése, kutyatámadások"
            }
        ];